universe = vanilla
executable = run_cmssw_job.sh
arguments = $(mode)

output = logs/job_$(mode).out
error  = logs/job_$(mode).err
log    = logs/job_$(mode).log


should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ConfFile_cfg.py, run_cmssw_job.sh

# Override default restrictive requirements
#requirements = (TARGET.OpSysAndVer == "AlmaLinux9") && (TARGET.Arch == "X86_64")

+JobFlavour = "longlunch"

queue mode from (
QCD
EWK
Interference
)
